### ISSUE TITLE
Crash trying to eager load optional parent

### ISSUE THREAD

**Issue by skyweb07** [vapor/fluent-kit#279]
Hey guys, I don't know if it's a bug or hasn't been implemented yet but right now when I try to 
eager load an optional eager loaded optional property from the model when they are all not null it works perfectly but when there's one that's is null it shows this error 

<img width="2152" alt="Screenshot 2020-05-19 at 18 30 11" src="https://user-images.githubusercontent.com/747750/82357059-d4dcac80-9a04-11ea-9e46-970b90a89972.png">

I think that's it's trying to eager load the model but as there is a force unwrap it crashes, this is the query I'm doing now

<img width="941" alt="Screenshot 2020-05-19 at 18 29 38" src="https://user-images.githubusercontent.com/747750/82357066-d908ca00-9a04-11ea-9983-3180bc6c9573.png">

If you can point me out I can send a pr and fix it, I've tried with the latest v4 and even the gm branch from fluent (Postgres) and it's still not working

Thanks!

**Comment by tanner0101** [comment]
I believe this is related to https://github.com/vapor/fluent-kit/issues/208 and has been fixed in https://github.com/vapor/fluent-kit/pull/270. Make sure you have this commit which contains the fix: https://github.com/vapor/fluent-kit/commit/989805e01b90b8465da2c80377d7f1ddd3621bd3#diff-b7fe39d8c878a5f8324a53c6fda3a5d9

Just to be sure, I tried to recreate your example (we have a test for this, but not with the exact same structure) and I was unable to repro.

**Comment by skyweb07** [comment]
> I believe this is related to #208 and has been fixed in #270. Make sure you have this commit which contains the fix: [989805e](https://github.com/vapor/fluent-kit/commit/989805e01b90b8465da2c80377d7f1ddd3621bd3)
> 
> Just to be sure, I tried to recreate your example (we have a test for this, but not with the exact same structure) and I was unable to repro.

I tried with the gm branch from fluent and still happening, will try to make a test repo to reproduce it
